### ISSUE TITLE
Use a modern functional programming approach

### ISSUE THREAD

**Issue by vlabs** [addania/challenge#3]
Declaration:
- [x] don't ever use `let` or `var` (for components)
- [x] don't ever use `let` or `var` (for eventHandlers)
- [x] don't ever use `let` or `var` (for helper functions)

Non-mutation:
- [x] don't use mutating functions such as `push`, `delete`, .. but `map`, `filter`,.. 

For loops:
- [x] don't use classic loops such as `for`,..

Lodash
- [x] don't use `lodash` when we have a native es6 function available, eg `filter`
- [x] use more `lodash` function to shorten your code (don't reinvent the wheel)

Pure functions:
- [x] use pure functions (same inputs always yields same output, no sideeffects)

**Arrow functions:**
- [x] use arrow functions (for components declaration)
- [x] use arrow functions (for eventHandlers)
- [x] use arrow functions (for helper functions)

Complexity:
- [x] also try to reduce complexity and reduce lines of code for all those functions that would be triggered by `parseData`

**Comment by addania** [comment]
@vlabs I think I am finished :) Merry Xmas and I am very much looking forward to your feedback! Maybe we could have a call or meeting to synch together.
