### ISSUE TITLE
Separate concerns

### ISSUE THREAD

**Issue by vlabs** [addania/challenge#4]
separate business logic from the presentation layer:
- [x]  move each helper function into a dedicated file
    - [x] csvJSON, 
    - [x] formatImpressions, 
    - [x] extractDate,
    - [x] sortArray, 
    - [x] getColumns, 
    - [x] getMetrics, 
    - [x] getDimensions, 
    - [x] getDates, 
    - [x] formatDate
    - [x] calculateOptions, 
    - [x] filterArray, 
    - [x] calculateAggregates, 
    - [x] generateOptions, 
    - [x] generateMessage, 
    - [x] generateList
    - [x] generateOptionsFilter
    - [x] business logic in `Filter` component
    - [x] business logic in `Subheader` component
    - [x] business logic in `App` component of `handle` functions
- [x] and add tests for them
     - [x] csvJSON, 
    - [x] formatImpressions, 
    - [x] extractDate,
    - [x] sortArray, 
    - [x] getColumns, 
    - [x] getMetrics, 
    - [x] getDimensions, 
    - [x] getDates, 
    - [x] formatDate
    - [x] calculateOptions, 
    - [x] filterArray, 
    - [x] calculateAggregates, 
    - [x] generateOptions, 
    - [x] generateMessage, 
    - [x] generateList
    - [x] generateOptionsFilter
    - [x] Button
    - [x] Header
    - [x] List
    - [x] App handleClickHelper
    - [x] App handleChangeHelper
    - [x] App itself
    - [x] Filter
    - [x] Subheader
    - [x] Chart

**Comment by addania** [comment]
@vlabs 

I am not entirely sure what is meant by:
separate:
```
business logic in Filter component
business logic in Subheader component
business logic in App component of handle functions
```
