### ISSUE TITLE
Properly include sematic ui css

### ISSUE THREAD

**Issue by vlabs** [addania/challenge#5]
remove this hack:
https://github.com/addania/challenge/blob/d35c781d6a8594fe2657e9b37d850453e1aa631d/src/components/Filter.js#L8-L12

**Comment by addania** [comment]
Hi Tom, this "hack" was from the official semantic ui website:
https://react.semantic-ui.com/modules/dropdown/

To view it in codesandbox:
https://codesandbox.io/s/9h0ck?module=/index.js

However, I could find another way how to integrate it with the following code in index.html:
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css" />

**Comment by vlabs** [comment]
yes, thats much better
