### ISSUE TITLE
Improve fetchData

### ISSUE THREAD

**Issue by vlabs** [addania/challenge#6]
https://github.com/addania/challenge/blob/d35c781d6a8594fe2657e9b37d850453e1aa631d/src/App.js#L30-L43

- [x]  `dates` can be removed
- [x]  reduce to four lines, eg
```
const { data, metrics, dimensions } = parseData(await response.text())
setData(data); 
setMetrics(metrics); 
setDimensions(dimensions); 
```

- [x] also try to reduce complexity and reduce lines of code for all those functions that would be triggered by `parseData`

**Comment by addania** [comment]
Last point will be handled here: https://github.com/addania/challenge/issues/3
